<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DTOs\" />
    <Folder Include="Features\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IMS.Domain\IMS.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Moq">
      <HintPath>C:\Users\User\.nuget\packages\moq\4.20.72\lib\net6.0\Moq.dll</HintPath>
    </Reference>
    <Reference Include="xunit.core">
      <HintPath>C:\Users\User\.nuget\packages\xunit.extensibility.core\2.9.3\lib\netstandard1.1\xunit.core.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
